apiVersion: v2
name: monitoring-stack
description: Prometheus & Grafana Monitoring Stack
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: kube-prometheus-stack
    version: 56.6.0
    repository: https://prometheus-community.github.io/helm-charts