apiVersion: v2
name: infrastructure
description: Databases and Messaging Queue
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:

  - name: postgresql
    version: 15.5.2
    repository: https://charts.bitnami.com/bitnami

  - name: mongodb
    version: 15.6.3
    repository: https://charts.bitnami.com/bitnami

  - name: redis
    version: 19.3.2
    repository: https://charts.bitnami.com/bitnami

  - name: strimzi-kafka-operator
    version: 0.38.0
    repository: https://strimzi.io/charts/
  
  - name: ingress-nginx
    version: 4.9.1
    repository: https://kubernetes.github.io/ingress-nginx